# Generated by Django 6.0.6 on 2026-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_interviewsession_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermidiate', 'Intermidiate'), ('Advance', 'Advance')], default='Beginner', max_length=50),
        ),
    ]
